### PR TITLE
2.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
This is a major update, rebooting the project:

 * Removed the Windows installer
 * Removed the WPF-based setup wizard
 * Removed the file-based import command - `seqcli` does this better
 * Renamed the executable to `seqfwd`, since setup is now via the command-line, and we'll type this a lot
 * Ported to .NET Core 3.1
 * Replaced NancyFX with ASP.NET Core
 * Added support for macOS and Linux
 * Set up zip/gzip release publishing
 * Added support for compact log event format (CLEF), aka `compact: true`
 * Added support for SSL certificate binding on Windows
 * Added support for sending internal diagnostics to a secondary Seq instance
 * Removed event payload fragments from the ingestion log unless opted-in

**Edit:** - for anyone keen to try out the new version: https://github.com/datalust/seq-forwarder/releases/tag/v2.0.97-pre

### CODE REVIEW

**Comment by xantari** [comment]
Whats the status on this PR?

**Comment by nblumhardt** [comment]
@xantari thanks for the nudge. I've just reviewed the open issue list and I don't think there's much if anything left to go.

Have you been able to try the latest `2.0.101` build from CI? It's at: https://ci.appveyor.com/project/datalust/seq-forwarder/builds/35649516/artifacts 

Would be great to know how you've gone with it, if so.

If anyone following can give a +1 vote of confidence in 2.0.101, the feedback would be appreciated. We'll press the button on this release as soon as we have some data.

**Comment by xantari** [comment]
I'll see if I can get it installed on a few boxes next week

**Comment by nblumhardt** [comment]
Ping! Has anyone had a shot at updating to the 2.0.0-dev versions? We'll hit the button on this next week, time to move the release forward :-)

**Pull request merged**
